apiVersion: v1
description: A Helm chart for Tekton Pipelines
name: metallb
version: 1.0.0
appVersion: 1.0.0
icon: https://raw.githubusercontent.com/metallb/metallb/main/website/static/images/logo/metallb-blue.png
home: https://github.com/jenkins-x-charts/metallb
