apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
  labels:
    app.kubernetes.io/component: metallb
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: metallb
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - "{{ .Values.address.from }}-{{ .Values.address.to | default .Values.address.from }}"