apiVersion: v1
data:
  secretkey: {{ randAlphaNum 128 | b64enc | quote }}
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
  labels:
    app.kubernetes.io/component: metallb
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: metallb
